In [1]:
import numpy as np
from scipy import stats
from scipy.stats import norm
import random

In [2]:
die1 = np.array([2,7,7,12,12,17])
die2 = np.array([3,8,8,13,13,18])
results = np.array([385,840,700,423])

In [3]:
stats.variation(die1)
std = (die1 + die2).std() * 20
mean = (die1 + die2).mean() * 20
mean, std

(400.0, 191.48542155126762)

In [4]:
z_scores = (results - mean) / std
z_scores

array([-0.07833495,  2.29782506,  1.5666989 ,  0.12011358])

In [5]:
final = np.array(list(map(lambda x: x if abs(norm.sf((x - mean) / std)) > .1 else 0, results)))
print(z_scores)
print(final)
final.argmax()

[-0.07833495  2.29782506  1.5666989   0.12011358]
[385   0   0 423]


3

In [6]:
class node:
    def __init__(self):
        self.options = ['n', 's', 'e', 'w']
        random.shuffle(self.options)

    def make_choice(self):
        if len(self.options) == 0: return None
        choice = self.options.pop()
        return choice
    def remove(self, direction):
        self.options.remove(direction)

In [7]:
def get_matrix(height, width):
    original_matrix = []
    for i in range(height):
        original_matrix.append([node() for _ in range(width)])

    for i in range(height):
        original_matrix[i][0].options.remove('w')
    for i in range(width):
        original_matrix[0][i].options.remove('n')
    for i in range(height):
        original_matrix[i][-1].options.remove('e')
    for i in range(width):
        original_matrix[-1][i].options.remove('s')
    original_matrix[0][0].options.remove('e')
    original_matrix[0][1].options.remove('w')
    original_matrix[0][1].options.remove('e')
    original_matrix[0][2].options.remove('w')
    original_matrix[-1][-1].options = []
    return original_matrix

In [8]:
def traverse(direction, cost:int, node1:node, node2:node):
    if direction == 'n':
        cost /= 2
        node2.options.remove('s')
        return cost
    if direction == 's':
        cost *= 2
        node2.options.remove('n')
        return cost
    if direction == 'e':
        cost += 2
        node2.options.remove('w')
        return cost
    if direction == 'w':
        cost -= 2
        node2.options.remove('e')
        return cost

In [9]:
starting_point = 0,2
num_iters = 0
height, width = 5, 5

In [10]:
def wander(starting_height=0, starting_width=2, cost=4, total_height=5, total_width=5):
    matrix = get_matrix(total_height, total_width)
    height, width = starting_height, starting_width
    node1 = matrix[starting_height][starting_width]
    path = []
    cost = 4
    num_iters = 0
    while height < total_height - 1 and width < total_width - 1 and len(node1.options) > 0:
        num_iters += 1
        if len(node1.options) == 0: break
        direction = node1.options.pop()
        path.append(direction)
        if direction == 'n': height -= 1
        if direction == 's': height += 1
        if direction == 'e': width += 1
        if direction == 'w': width -= 1
        node2 = matrix[height][width]
        cost = traverse(direction=direction, cost=cost, node1=node1, node2=node2)
        node1 = node2
    if cost > 0: return None
    if height != total_height - 1: return None
    if width != total_width - 1: return None
    if cost < 0: print(f'error: cost is {cost} at path {path}')
    return path

In [11]:
def go_wander():
    path = None
    while num_iters < 9999999999 and path is None:
        path = wander()
    if path is None: print('did not find answer')
    else:
        print('answer:')
        print(path)

In [20]:
for i in range(101,201):
    print(i * 7 * 11 * 13)

101101
102102
103103
104104
105105
106106
107107
108108
109109
110110
111111
112112
113113
114114
115115
116116
117117
118118
119119
120120
121121
122122
123123
124124
125125
126126
127127
128128
129129
130130
131131
132132
133133
134134
135135
136136
137137
138138
139139
140140
141141
142142
143143
144144
145145
146146
147147
148148
149149
150150
151151
152152
153153
154154
155155
156156
157157
158158
159159
160160
161161
162162
163163
164164
165165
166166
167167
168168
169169
170170
171171
172172
173173
174174
175175
176176
177177
178178
179179
180180
181181
182182
183183
184184
185185
186186
187187
188188
189189
190190
191191
192192
193193
194194
195195
196196
197197
198198
199199
200200
